# Multi Container Pod 
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod 
spec:
  containers:
  - name: nginx-cnt
    image: nginx:latest 

  - name: centos-cnt
    image: centos:7
    command: ['sleep' , "600"]  