apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
data:
  # property-like keys; each key maps to a simple value
  age: "26"
  name: "Saurabh"
  ENV: "Dev"

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-ctr
    image: nginx:latest 
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: cm
    env:
      - name: Manager
        value: "Saurabh"  

  

