#Secrets         #echo RGV2T3BzMzIxCg== | base64 --decode

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  db_user: YWRtaW4K                         #admin
  db_pass: RGV2T3BzMzIxCg==                 #DevOps321

---
apiVersion: v1
kind: Pod
metadata:
  name: payment
spec:
  containers:
  - name: nginx-ctr
    image: nginx:latest 
    ports:
      - containerPort: 80
    # envFrom:
    #   - configMapRef:
    #       name: cm
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: db-user