apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: payment-set
  labels:
    app: guestbook
    tier: payment
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: payment
  template:
    metadata:
      labels:
        tier: payment
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl