#Deployment Strategy - Recreate
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   labels:
#     app: nginx
# spec:
#   replicas: 10
#   selector:
#     matchLabels:
#       app: nginx
#   strategy: 
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:perl
#         ports:
#         - containerPort: 80
---
#Deployment Strategy - RollingUpdate
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rollingupdate
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  strategy: 
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
        ports:
        - containerPort: 80