#Deployment Strategy - Recreate
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   labels:
#     app: nginx
# spec:
#   replicas: 10
#   selector:
#     matchLabels:
#       app: nginx
#   strategy: 
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:perl
#         ports:
#         - containerPort: 80
---
#Deployment Strategy - RollingUpdate
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 10
  selector:
    matchLabels:
      app: httpd
  strategy: 
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 5
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80