apiVersion: v1
kind: Service
metadata:
  name: nginx-1-svc
spec:
  selector:
    app: nginx-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1-deployment
  labels:
    app: nginx-1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 5
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx-1
        image: nginx
        ports:
        - containerPort: 80