apiVersion: v1
kind: Service
metadata:
  name: nginx-2-svc
spec:
  selector:
    app: nginx-2
  ports:
    - protocol: TCP
      port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2-deployment
  labels:
    app: nginx-2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 5
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx-2
        image: nginx
        ports:
        - containerPort: 80