#Namespace for payment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app
  namespace: payment
  labels:
    app: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: httpd
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: payment-svc
  namespace: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

#Namespace for user
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  namespace: user
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: httpd
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


# <serviceName>.<nameSpace>.svc.cluster.local
# curl user-svc.user.svc.cluster.local